export const cards = [
    {
        titulo: "Primeros pasos",
        detalle: "Primer modulo completado del nivel básico",
        significado: "La anaconda",            
        imgSrc: "/img/achievements/anaconda.png",
        descripcion: "El diseño de la anaconda representa la energía vital de la creación. Es llevado por los yachak en eventos ceremoniales y culturales de la comunidad.",            
        unlockLevel: 6,  
    },
    {
        titulo: "Aprendiendo poco a poco",
        detalle: "Has completado el segundo módulo nivel básico",
        significado: "Lumu tarpuna",            
        imgSrc: "/img/achievements/lumu-tarpuna.png",
        descripcion: "Este diseño representa la siembra de la yuca que la mujer realiza en su huerta. Es de uso exclusivo de la mujer.",            
        unlockLevel: 13,  
    },
    {
        titulo: "Sabemos lo básico",
        detalle: "Tercer módulo del el nivel básico completado",
        significado: "Kuyllur y Duziru",            
        imgSrc: "/img/achievements/Kuyllur_Duziru.png",
        descripcion: "Este diseño representa el poder, la fuerza, la valentía y la sabiduría. Esta figura se utiliza cuando una persona va a la guerra, a la cacería, o participa en los rituales y ceremonias.",            
        unlockLevel: 19,
    },
    {
        titulo: "Vamos por el siguiente nivel",
        detalle: "Primer modulo completado del nivel intermedio",
        significado: "Amazanka",            
        imgSrc: "/img/achievements/Amazanka.png",
        descripcion: "Este diseño es usado por los/as niños/as, para recibir el poder, el conocimiento y la inteligencia del Amazanka, a fin de resistir las caminatas por la selva, por donde ha caminado el Amazanka",            
        unlockLevel: 26,
    },
    {
        titulo: "Ya queremos hablar y escribir",
        detalle: "Estas en la mitad del nivel intermedio",
        significado: "Anka, ñanpi y yawati",            
        imgSrc: "/img/achievements/Anka_Nanpi_Yawati.png",
        descripcion: "El diseño de aves y animales son representadas en el rostro de las personas para adquirir sus poderes y destrezas en la cotidianidad.",            
        unlockLevel: 36,
    },
    {
        titulo: "Sabemos Kichwa",
        detalle: "Terminaste el nivel intermedio",
        significado: "Charapa",            
        imgSrc: "/img/achievements/Charapa.png",
        descripcion: "Es de uso exclusivo del varón. Se diseñan en ocasiones de singular importancia comunitaria, dirigidas a la solución de los problemas.",            
        unlockLevel: 52,
    }
];