export const cards = [
    {
        titulo: "Primeros pasos",
        titulobanner: "Nivel básico, módulo 1",
        Banner: "/img/cover/basic-m1-1.jpg",
        detalle: "Primer módulo completado del nivel básico",
        significado: "La anaconda",            
        imgSrc: "/img/achievements/anaconda.png",
        descripcion: "El diseño de la anaconda representa la energía vital de la creación. Es llevado por los yachak en eventos ceremoniales y culturales de la comunidad.",            
        unlockLevel: 6,  
    },
    {
        titulo: "Aprendiendo poco a poco",
        titulobanner: "Nivel básico, módulo 2",
        Banner: "/img/cover/basic-m2-1.jpg",
        detalle: "Segundo módulo completado del nivel básico",
        significado: "Lumu tarpuna",            
        imgSrc: "/img/achievements/lumu-tarpuna.png",
        descripcion: "Este diseño representa la siembra de la yuca que la mujer realiza en su huerta. Es de uso exclusivo de la mujer.",            
        unlockLevel: 13,  
    },
    {
        titulo: "Sabemos lo básico",
        titulobanner: "Nivel básico, módulo 3",
        Banner: "/img/cover/basic-m3-1.jpg",
        detalle: "Tercer módulo completado del nivel básico",        
        significado: "El rayu",            
        imgSrc: "/img/achievements/Rayu.png",
        descripcion: "La figura del hombre Rayu, recalca el papel que ejerce una persona, al controlar un grupo. Expresa el poder del líder. ",            
        unlockLevel: 19,
    },
    {
        titulo: "De lo básico a lo sorprendente",
        titulobanner: "Nivel intermedio, módulo 1",
        Banner: "/img/cover/intermediate-m1-2.jpg",
        detalle: "Primer módulo completado del nivel intermedio",
        significado: "Kuyllur y Duziru",            
        imgSrc: "/img/achievements/Kuyllur_Duziru.png",
        descripcion: "Este diseño es usado por los/as niños/as, para recibir el poder, el conocimiento y la inteligencia del Amazanka, a fin de resistir las caminatas por la selva, por donde ha caminado el Amazanka",            
        unlockLevel: 26,

    },
    {
        titulo: "Preguntar y conectar",
        titulobanner: "Nivel intermedio, módulo 2",
        Banner: "/img/cover/intermediate-m2-2.jpg",
        detalle: "Segundo módulo completado del nivel intermedio",
        significado: "Amazanka",            
        imgSrc: "/img/achievements/Amazanka.png",
        descripcion: "Este diseño es usado por los/as niños/as, para recibir el poder, el conocimiento y la inteligencia del Amazanka, a fin de resistir las caminatas por la selva, por donde ha caminado el Amazanka",            
        unlockLevel: 33,
    },
    {
        titulo: "Del verbo a la acción",
        titulobanner: "Nivel intermedio, módulo 3",
        Banner: "/img/cover/intermediate-m3-2.jpg",
        detalle: "Tercer módulo completado del nivel intermedio",
        significado: "Búho (Bullukuku)",            
        imgSrc: "/img/achievements/Buho.png",
        descripcion: "Este diseño es usado especialmente por los niños/as, para recibir el poder, el conocimiento y la inteligencia del búho.",            
        unlockLevel: 40,
    },
    {
        titulo: "Viajando en el tiempo",
        titulobanner: "Nivel intermedio, módulo 4",
        Banner: "/img/cover/intermediate-m4-2.jpg",
        detalle: "Cuarto módulo completado del nivel intermedio",
        significado: "Anka, ñanpi y yawati",            
        imgSrc: "/img/achievements/Anka_Nanpi_Yawati.png",
        descripcion: "El diseño de aves y animales son representadas en el rostro de las personas para adquirir sus poderes y destrezas en la cotidianidad.",            
        unlockLevel: 47,
    },
    {
        titulo: "El presente y el futuro",
        titulobanner: "Nivel intermedio, módulo 5",
        Banner: "/img/cover/intermediate-m5-2.jpg",
        detalle: "Quinto módulo completado del nivel intermedio",
        significado: "Charapa",            
        imgSrc: "/img/achievements/Charapa.png",
        descripcion: "Es de uso exclusivo del varón. Se diseñan en ocasiones de singular importancia comunitaria, dirigidas a la solución de los problemas.",            
        unlockLevel: 52,
    }
];