import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-icons/font/bootstrap-icons.min.css'
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import BootstrapClient from '@/app/components/BootstrapClient.js';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Yachasum Kichwa</title>
      </head>
      <body>
        <body className={inter.className}>
          <Navbar />
          {children}
          <BootstrapClient />
          <Footer />
        </body>

      </body>
    </html>
  )
}


